# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\valeg\Documents\IoT\iot_g4\Tarea2\Raspberry\extra\qt\esp_found_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_esp_found_item(object):
    def setupUi(self, Form_esp_found_item):
        Form_esp_found_item.setObjectName("Form_esp_found_item")
        Form_esp_found_item.resize(840, 31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_esp_found_item.sizePolicy().hasHeightForWidth())
        Form_esp_found_item.setSizePolicy(sizePolicy)
        self.horizontalLayout_esp_found_item = QtWidgets.QHBoxLayout(Form_esp_found_item)
        self.horizontalLayout_esp_found_item.setContentsMargins(20, 1, 20, 1)
        self.horizontalLayout_esp_found_item.setObjectName("horizontalLayout_esp_found_item")
        self.label_esp_found_tag = QtWidgets.QLabel(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp_found_tag.sizePolicy().hasHeightForWidth())
        self.label_esp_found_tag.setSizePolicy(sizePolicy)
        self.label_esp_found_tag.setScaledContents(False)
        self.label_esp_found_tag.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_esp_found_tag.setIndent(0)
        self.label_esp_found_tag.setObjectName("label_esp_found_tag")
        self.horizontalLayout_esp_found_item.addWidget(self.label_esp_found_tag)
        self.horizontalLayout_esp_found_id = QtWidgets.QHBoxLayout()
        self.horizontalLayout_esp_found_id.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_esp_found_id.setObjectName("horizontalLayout_esp_found_id")
        self.label_esp_found_id_tag = QtWidgets.QLabel(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp_found_id_tag.sizePolicy().hasHeightForWidth())
        self.label_esp_found_id_tag.setSizePolicy(sizePolicy)
        self.label_esp_found_id_tag.setObjectName("label_esp_found_id_tag")
        self.horizontalLayout_esp_found_id.addWidget(self.label_esp_found_id_tag)
        self.label_esp_found_id_edit = QtWidgets.QLabel(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp_found_id_edit.sizePolicy().hasHeightForWidth())
        self.label_esp_found_id_edit.setSizePolicy(sizePolicy)
        self.label_esp_found_id_edit.setObjectName("label_esp_found_id_edit")
        self.horizontalLayout_esp_found_id.addWidget(self.label_esp_found_id_edit)
        self.horizontalLayout_esp_found_item.addLayout(self.horizontalLayout_esp_found_id)
        self.horizontalLayout_esp_found_mac = QtWidgets.QHBoxLayout()
        self.horizontalLayout_esp_found_mac.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_esp_found_mac.setObjectName("horizontalLayout_esp_found_mac")
        self.label_esp_found_mac_tag = QtWidgets.QLabel(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp_found_mac_tag.sizePolicy().hasHeightForWidth())
        self.label_esp_found_mac_tag.setSizePolicy(sizePolicy)
        self.label_esp_found_mac_tag.setObjectName("label_esp_found_mac_tag")
        self.horizontalLayout_esp_found_mac.addWidget(self.label_esp_found_mac_tag)
        self.label_esp_found_mac_edit = QtWidgets.QLabel(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_esp_found_mac_edit.sizePolicy().hasHeightForWidth())
        self.label_esp_found_mac_edit.setSizePolicy(sizePolicy)
        self.label_esp_found_mac_edit.setObjectName("label_esp_found_mac_edit")
        self.horizontalLayout_esp_found_mac.addWidget(self.label_esp_found_mac_edit)
        self.horizontalLayout_esp_found_item.addLayout(self.horizontalLayout_esp_found_mac)
        self.pushButton_esp_found_add = QtWidgets.QPushButton(Form_esp_found_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_esp_found_add.sizePolicy().hasHeightForWidth())
        self.pushButton_esp_found_add.setSizePolicy(sizePolicy)
        self.pushButton_esp_found_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_add/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_esp_found_add.setIcon(icon)
        self.pushButton_esp_found_add.setObjectName("pushButton_esp_found_add")
        self.horizontalLayout_esp_found_item.addWidget(self.pushButton_esp_found_add)
        self.horizontalLayout_esp_found_item.setStretch(0, 4)
        self.horizontalLayout_esp_found_item.setStretch(1, 2)
        self.horizontalLayout_esp_found_item.setStretch(2, 3)

        self.retranslateUi(Form_esp_found_item)
        QtCore.QMetaObject.connectSlotsByName(Form_esp_found_item)

    def retranslateUi(self, Form_esp_found_item):
        _translate = QtCore.QCoreApplication.translate
        Form_esp_found_item.setWindowTitle(_translate("Form_esp_found_item", "Form"))
        self.label_esp_found_tag.setText(_translate("Form_esp_found_item", "ESP-32"))
        self.label_esp_found_id_tag.setText(_translate("Form_esp_found_item", "ID: "))
        self.label_esp_found_id_edit.setText(_translate("Form_esp_found_item", "1110"))
        self.label_esp_found_mac_tag.setText(_translate("Form_esp_found_item", "mac: "))
        self.label_esp_found_mac_edit.setText(_translate("Form_esp_found_item", "aa-aa-aa"))
from . import icons_rc
