-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 00:44:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema IoT_Tarea2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IoT_Tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IoT_Tarea2` ;
USE `IoT_Tarea2` ;

-- -----------------------------------------------------
-- Table `IoT_Tarea2`.`Configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_Tarea2`.`Configuration` (
  `id_device` INT NOT NULL,
  `status_conf` INT NULL,
  `protocol_conf` INT NULL,
  `acc_sampling` INT NULL,
  `acc_sensibility` INT NULL,
  `gyro_sensibility` INT NULL,
  `bme688_sampling` INT NULL,
  `discontinuos_time` INT NULL,
  `tcp_port` INT NULL,
  `udp_port` INT NULL,
  `host_ip_addr` INT UNSIGNED NULL,
  `ssid` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id_device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IoT_Tarea2`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_Tarea2`.`Log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_report` INT NULL,
  `protocol_report` INT NULL,
  `battery_level` INT NULL,
  `conf_peripheral` INT NULL,
  `time_client` INT NULL,
  `time_server` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Configuration_id_device` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Log_Configuration_idx` (`Configuration_id_device` ASC) VISIBLE,
  CONSTRAINT `configuration.id_device`
    FOREIGN KEY (`Configuration_id_device`)
    REFERENCES `IoT_Tarea2`.`Configuration` (`id_device`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IoT_Tarea2`.`Data_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_Tarea2`.`Data_test` (
  `id_device` INT NOT NULL,
  `temperature` INT NULL,
  `press` INT NULL,
  `hum` INT NULL,
  `co` FLOAT NULL,
  `rms` FLOAT NULL,
  `amp_x` FLOAT NULL,
  `freq_x` FLOAT NULL,
  `amp_y` FLOAT NULL,
  `freq_y` FLOAT NULL,
  `amp_z` FLOAT NULL,
  `freq_z` FLOAT NULL,
  PRIMARY KEY (`id_device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IoT_Tarea2`.`Data_acceloremeter_sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_Tarea2`.`Data_acceloremeter_sensor` (
  `id_device` INT NOT NULL,
  `Log_id` INT NOT NULL,
  `data_acceloremeter_sensor` JSON NULL,
  PRIMARY KEY (`id_device`, `Log_id`),
  INDEX `fk_Data_acc_sensor_Log_idx` (`Log_id` ASC) VISIBLE,
  CONSTRAINT `fk_Data_acc_sensor_Log`
    FOREIGN KEY (`Log_id`)
    REFERENCES `IoT_Tarea2`.`Log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IoT_Tarea2`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_Tarea2`.`Data` (
  `id_device` INT NOT NULL,
  `Log_id` INT NOT NULL,
  `data` JSON NULL,
  PRIMARY KEY (`id_device`, `Log_id`),
  INDEX `fk_Data_Log_idx` (`Log_id` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Log`
    FOREIGN KEY (`Log_id`)
    REFERENCES `IoT_Tarea2`.`Log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
